//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trytry.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class bookingtable
    {
        public int BookingId { get; set; }
        public Nullable<int> TableId { get; set; }
        public string HallName { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "User Name")]
        [RegularExpression("[A-Za-z]*", ErrorMessage = "Invalid Name ")]
        public string Name { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Cell #")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$",
                   ErrorMessage = "Entered phone format is not valid.(3*********")]
        public Nullable<int> Phone_No { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [RegularExpression("([a-zA-Z0-9_ .&'-]+)", ErrorMessage = "Invalid.")]
        public string Address { get; set; }


        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Check in Date")]
        [DataType(DataType.Date)]
        public string checkindate { get; set; }


        public Nullable<System.TimeSpan> Time { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "No of Persons")]
        [MinLength(1)]
        [RegularExpression("[^0-9]", ErrorMessage = "Input must be numeric")]
        public Nullable<int> personno { get; set; }
    
        public virtual tableadmin1 tableadmin1 { get; set; }
        public virtual tablebooking tablebooking { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
