//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trytry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookingtable
    {
        public int BookingId { get; set; }
        public Nullable<int> TableId { get; set; }
        public string HallName { get; set; }
        public string Name { get; set; }
        public Nullable<int> Phone_No { get; set; }
        public string Address { get; set; }
        public string checkindate { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<int> personno { get; set; }
    
        public virtual tablebooking tablebooking { get; set; }
    }
}
