//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trytry.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    using System.Web;
    
    public partial class City
    {
        public int CityId { get; set; }


        public HttpPostedFileBase ImageFile { get; set; }
        [DisplayName("CityName")]
        [Required(ErrorMessage = "CityName is required.")]
        [StringLength(50)]
        [DataType(DataType.Text)]
        public string CityName { get; set; }


        [DisplayName("Upload File")]
        public string image { get; set; }
        
    }
}
