//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trytry.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    using System.ComponentModel.DataAnnotations;
    
    public partial class City
    {
        public int CityId { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public string CityName { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public string image { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
