//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trytry.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    using System.ComponentModel.DataAnnotations;
    
    public partial class conference
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public conference()
        {
            this.conferencebookings = new HashSet<conferencebooking>();
        }
    
        public int HallId { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public string CityName { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public string HallName { get; set; }


        public string facilities { get; set; }
        public byte[] image { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name ="Snacks")]
        [RegularExpression("[A-Za-z]*", ErrorMessage = "Invalid Input ")]
        public string fooditems { get; set; }


        [Required(ErrorMessage = "This field is required")]
        [MinLength(1)]
        [RegularExpression("[^0-9]", ErrorMessage = "Input must be numeric")]
        public Nullable<int> capacity { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [DataType(DataType.Date)]
        public string date { get; set; }


        [Required(ErrorMessage = "This field is required")]
        [DataType(DataType.Time)]
        public string time { get; set; }


        [Required(ErrorMessage = "This field is required")]
        [MinLength(1)]
        [RegularExpression("[^0-9]", ErrorMessage = "Input must be numeric")]
        public Nullable<int> budget { get; set; }


        [Required(ErrorMessage = "This field is required")]
        [ RegularExpression("([a-zA-Z0-9_ .&'-]+)", ErrorMessage = "Invalid.")]
        public string address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<conferencebooking> conferencebookings { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
