//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trytry.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;


    public partial class conference
    {
        public int HallId { get; set; }



        [DisplayName("CityName")]
        [Required(ErrorMessage = "CityName is required.")]
        [StringLength(50)]
        [DataType(DataType.Text)]

        public string CityName { get; set; }



        [DisplayName("HallName")]
        [Required(ErrorMessage = "HallName is required.")]
        [StringLength(50)]
        [DataType(DataType.Text)]
        public string HallName { get; set; }



        [DisplayName("facilities")]
        [Required(ErrorMessage = "facilities is required.")]
        [StringLength(50)]
        [DataType(DataType.Text)]
        public string facilities { get; set; }


        public byte[] image { get; set; }



        [DisplayName("FoodItems")]
        [Required(ErrorMessage = "FoodItems are required.")]
        [StringLength(50)]
        [DataType(DataType.Text)]
        public string fooditems { get; set; }

        [DisplayName("capacity")]
        [Required(ErrorMessage = "capacity is required.")]
        [StringLength(50)]

        public Nullable<int> capacity { get; set; }


        [DisplayName("Date")]
        [Required(ErrorMessage = "Date is required.")]
        [StringLength(50)]
        [DataType(DataType.DateTime)]
        public string date { get; set; }

        [DisplayName("Time")]
        [Required(ErrorMessage = "time is required.")]
        [StringLength(50)]
        [DataType(DataType.DateTime)]
        public string time { get; set; }


        [DisplayName("budget")]
        [Required(ErrorMessage = "budget is required.")]
        [StringLength(50)]
        [DataType(DataType.Currency)]
        public Nullable<int> budget { get; set; }

        [DisplayName("address")]
        [Required(ErrorMessage = "address is required.")]
        [StringLength(150)]
        [DataType(DataType.PostalCode)]
        public string address { get; set; }
    }
}
