//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trytry.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class conference
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public conference()
        {
            this.conferencebookings = new HashSet<conferencebooking>();
        }
    
        public int HallId { get; set; }
        public string CityName { get; set; }
        public string HallName { get; set; }
        public string facilities { get; set; }
        public byte[] image { get; set; }
        public string fooditems { get; set; }
        public Nullable<int> capacity { get; set; }
        [Display(Name = "Check In Date")]
        [DataType(DataType.Date)]
        public string date { get; set; }
        public string time { get; set; }
        public Nullable<int> budget { get; set; }
        public string address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<conferencebooking> conferencebookings { get; set; }
    }
}
