//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trytry.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    public partial class hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hotel()
        {
            this.roombookingssssssses = new HashSet<roombookingsssssss>();
        }
        
        public int HotelId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string hotelname { get; set; }
        public string address { get; set; }
        public string roomtype { get; set; }
        public string facilities { get; set; }
        public byte[] image { get; set; }
        public Nullable<int> budget { get; set; }
        public string avaliablerooms { get; set; }
        [Display(Name = "Check In Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> checkindate { get; set; }
        [Display(Name = "Check out Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> checkoutdate { get; set; }
        public string CityName { get; set; }
    
        public virtual c c { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<roombookingsssssss> roombookingssssssses { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
