//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trytry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel
    {
        public int HotelId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string hotelname { get; set; }
        public string address { get; set; }
        public string roomtype { get; set; }
        public string facilities { get; set; }
        public byte[] image { get; set; }
        public Nullable<int> budget { get; set; }
        public string avaliablerooms { get; set; }
        public Nullable<System.DateTime> checkindate { get; set; }
        public Nullable<System.DateTime> checkoutdate { get; set; }
    
        public virtual c c { get; set; }
    }
}
