//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trytry.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class hoteladmin
    {
        public HttpPostedFileBase ImageFile { get; set; }
        public int HotelId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string hotelname { get; set; }
        public string address { get; set; }
        public string roomtype { get; set; }
        public string facilities { get; set; }
        public string image { get; set; }
        public Nullable<int> budget { get; set; }
        public Nullable<int> avaliablerooms { get; set; }
        public Nullable<System.DateTime> checkindate { get; set; }
        public Nullable<System.DateTime> checkoutdate { get; set; }
        public string CityName { get; set; }
    }
}
