
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trytry.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;

    public partial class hotel
    {
        public int HotelId { get; set; }
        public Nullable<int> CityId { get; set; }
        [DisplayName("hotelname")]
        [Required(ErrorMessage = "hotelname is required.")]
        [StringLength(50)]
        [DataType(DataType.Text)]
        public string hotelname { get; set; }



        [DisplayName("address")]
        [Required(ErrorMessage = "address is required.")]
        [StringLength(150)]
        [DataType(DataType.PostalCode)]
        public string address { get; set; }


        [DisplayName("roomtype")]
        [Required(ErrorMessage = "roomtype is required.")]
        [StringLength(150)]
        [DataType(DataType.Text)]
        public string roomtype { get; set; }





        [DisplayName("facilities")]
        [Required(ErrorMessage = "facilities is required.")]
        [StringLength(50)]
        [DataType(DataType.Text)]
        public string facilities { get; set; }

        [DataType(DataType.ImageUrl)]
        public byte[] image { get; set; }






        [DisplayName("budget")]
        [Required(ErrorMessage = "budget is required.")]
        [StringLength(50)]
        [DataType(DataType.Currency)]
        public Nullable<int> budget { get; set; }





        [DisplayName("availablerooms")]
        [Required(ErrorMessage = "availablerooms is required.")]
        [StringLength(50)]
        [DataType(DataType.Text)]

        public string avaliablerooms { get; set; }




        [DisplayName("checkinDate")]
        [Required(ErrorMessage = "checkinDate is required.")]
        [StringLength(50)]
        [DataType(DataType.Date)]

        public Nullable<System.DateTime> checkindate { get; set; }


        [DisplayName("checkoutDate")]
        [Required(ErrorMessage = "checkoutDate is required.")]
        [StringLength(50)]
        [DataType(DataType.Date)]

        public Nullable<System.DateTime> checkoutdate { get; set; }
        public virtual c c { get; set; }
    }
}
