//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trytry.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hotelEntities5 : DbContext
    {
        public hotelEntities5()
            : base("name=hotelEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<c> c { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<conference> conferences { get; set; }
        public virtual DbSet<hotel> hotels { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Sign_In> Sign_In { get; set; }
        public virtual DbSet<tablebooking> tablebookings { get; set; }
        public virtual DbSet<wedding> weddings { get; set; }
    }
}
