//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trytry.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hotelEntities8 : DbContext
    {
        public hotelEntities8()
            : base("name=hotelEntities8")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bookingtable> bookingtables { get; set; }
        public virtual DbSet<c> c { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<conference> conferences { get; set; }
        public virtual DbSet<conferenceadmin1> conferenceadmin1 { get; set; }
        public virtual DbSet<conferencebooking> conferencebookings { get; set; }
        public virtual DbSet<ContactU> ContactUs { get; set; }
        public virtual DbSet<hotel> hotels { get; set; }
        public virtual DbSet<hoteladmin1> hoteladmin1 { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<roombooking2> roombooking2 { get; set; }
        public virtual DbSet<roombookingsssssss> roombookingssssssses { get; set; }
        public virtual DbSet<Sign_In> Sign_In { get; set; }
        public virtual DbSet<tableadmin1> tableadmin1 { get; set; }
        public virtual DbSet<tablebooking> tablebookings { get; set; }
        public virtual DbSet<wedding1> wedding1 { get; set; }
        public virtual DbSet<weddingbooking> weddingbookings { get; set; }
    }
}
