//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trytry.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class roombooking2
    {
        public int BookingId { get; set; }
        public Nullable<int> HotellId { get; set; }
        public Nullable<int> Roomno { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name ="User Name")]
        [RegularExpression("[A-Za-z]*", ErrorMessage = "Invalid Name ")]
        public string Name { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Cell #")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$",
                   ErrorMessage = "Entered phone format is not valid.(3*********")]
        public Nullable<int> Phoneno { get; set; }


        [Required(ErrorMessage = "This field is required")]
        [RegularExpression("([a-zA-Z0-9_ .&'-]+)", ErrorMessage = "Invalid.")]
        public string Address { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Check in Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> checkindate { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Check out Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> checkoutdate { get; set; }
        public string Hallname { get; set; }
    
        public virtual hoteladmin1 hoteladmin1 { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
