//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trytry.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;

    public partial class tablebooking
    {
        public int TableId { get; set; }



        [DisplayName("CityName")]
        [Required(ErrorMessage = "CityName is required.")]
        [StringLength(50)]
        [DataType(DataType.Text)]


        public string CityName { get; set; }


        [DisplayName("HallName")]
        [Required(ErrorMessage = "HallName is required.")]
        [StringLength(50)]
        [DataType(DataType.Text)]


        public string HallName { get; set; }


        [DisplayName("address")]
        [Required(ErrorMessage = "address is required.")]
        [StringLength(150)]
        [DataType(DataType.PostalCode)]
        public string address { get; set; }


        [Required]
        public Nullable<int> personno { get; set; }



        [DisplayName("Date")]
        [Required(ErrorMessage = "Date is required.")]
        [StringLength(50)]
        [DataType(DataType.DateTime)]

        public Nullable<System.DateTime> date { get; set; }


        [DisplayName("startTime")]
        [Required(ErrorMessage = "starttime is required.")]
        [StringLength(50)]
        [DataType(DataType.DateTime)]
        public Nullable<System.TimeSpan> starttime { get; set; }


        [DisplayName("endTime")]
        [Required(ErrorMessage = "endtime is required.")]
        [StringLength(50)]
        [DataType(DataType.DateTime)]
        public Nullable<System.TimeSpan> endtime { get; set; }



        [DisplayName("budget")]
        [Required(ErrorMessage = "budget is required.")]
        [StringLength(50)]
        [DataType(DataType.Currency)]

        public Nullable<int> budget { get; set; }


        [Required]
        public byte[] image { get; set; }
    }
}
