//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trytry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wedding
    {
        public int HallId { get; set; }
        public string CityName { get; set; }
        public string HallName { get; set; }
        public string facilities { get; set; }
        public byte[] image { get; set; }
        public string fooditems { get; set; }
        public Nullable<int> capacity { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
        public Nullable<int> budget { get; set; }
        public string address { get; set; }
    }
}
