//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trytry.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class wedding1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wedding1()
        {
            this.weddingbookings = new HashSet<weddingbooking>();
        }
    
        public HttpPostedFileBase ImageFile { get; set; }
        public int HallId { get; set; }
        public string CityName { get; set; }
        public string HallName { get; set; }
        public string facilities { get; set; }
        public string image { get; set; }
        public string fooditems { get; set; }
        public Nullable<int> capacity { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
        public Nullable<int> budget { get; set; }
        public string address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<weddingbooking> weddingbookings { get; set; }
    }
}
